[project]
name = "backend"
version = "0.1.0"
description = "Backend for some project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "pyright>=1.1.401",
    "uvicorn>=0.34.2",
]

[tool.pyright]
include = ["src", "tests"]
venvPath = "."
venv = ".venv"
