[project]
name = "backend"
version = "0.1.0"
description = "Backend for some project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "unicorn>=2.1.3",
]
